version: '3'
services:
  redis-server:
    image: 'redis:7.0'
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 20s
      timeout: 60s
      start_period: 15s
    expose:
     - 6379
  
  # Deploy the mysql to aws ecs seems memory-heavy, switch to sqllite to save some resources
  #db:
  #  image: mysql
  #  command: '--default-authentication-plugin=mysql_native_password'
  #  restart: always
  #  healthcheck:
  #    test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password=secret --silent']
  #    interval: 20s
  #    timeout: 60s
  #    start_period: 15s
  #  environment:
  #    MYSQL_ROOT_PASSWORD: secret
  #    MYSQL_DATABASE: nothanks
  #  expose:
  #   - 3306

  django:
    build: django
    ports:
      - "8080:80"
    depends_on:
      redis-server:
        condition: service_healthy
      #db:
      #  condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
    #volumes:
    #  - ./django/:/usr/src/app