# Generated by Django 4.1.2 on 2022-10-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nothanks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='room_uid',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='token',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
