# Generated by Django 4.1.2 on 2022-10-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nothanks', '0002_alter_game_room_uid_alter_player_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='token',
            field=models.CharField(max_length=36),
        ),
    ]
