# Generated by Django 4.1.2 on 2022-10-20 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nothanks', '0003_alter_player_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
